---
kind: breed
name: sava-requester
deployable:
  type: application/javascript
  definition: |
    'use strict';

    var net = require('net');
    var client = new net.Socket();
    var vamp = require('vamp-node-client');

    var api = new vamp.Api();

    var vga;

    var process = function () {
      if (!vga) {
        api.config(function (config) {
          vga = config['vamp.gateway-driver.host'];
        });
      } else {

        client.connect(9057, vga, function() {
          client.write('*');
        });

        client.on('data', function(data) {
          api.event(['workflows:sava-requester', 'response:ok'], JSON.parse(data));
        });
      }
    };

    setInterval(process, 1000);

---
kind: workflow
name: sava-requester
breed: sava-requester
schedule: daemon