---
kind: breed
name: runner-requester
deployable:
  type: application/javascript
  definition: |
    'use strict';

    var _ = require('highland');
    var vamp = require('vamp-node-client');
    var http = require('request-promise');

    var vga;
    var api = new vamp.Api();

    var process = function () {
      if (!vga) {
        api.config().each(function (config) {
          vga = config['vamp.gateway-driver.host'];
        });
      } else {
        http('http://' + vga + ':9052/***').promise().then(function (body) {
          var result = JSON.parse(body);
          var result = JSON.parse(body);
          if (result['id'] === 'backend' && result['port'] === 8085 && result['path'] === '***') {
            api.event(['workflows:runner-requester', 'response:ok'], body);
          } else {
            api.event(['workflows:runner-requester', 'response:failed'], body);
          }
        });
      }
    };

    setInterval(process, 1000);

---
kind: workflow
name: runner-requester
breed: runner-requester
schedule: daemon