---
kind: breed
name: runner-requester
deployable:
  type: application/javascript
  definition: |
    'use strict';

    var http = require('request');
    var vamp = require('vamp-node-client');

    var api = new vamp.Api();

    var vga;

    var process = function () {
      if (!vga) {
        api.config(function (config) {
          vga = config['vamp.gateway-driver.host'];
        });
      } else {
        http('http://' + vga + ':9052/***', function (error, response, body) {
          if (!error && response.statusCode == 200) {
            var result = JSON.parse(body);
            if (result['id'] === 'backend' && result['port'] === 8085 && result['path'] === '***') {
              api.event(['workflows:runner-requester', 'response:ok'], body);
            } else {
              api.event(['workflows:runner-requester', 'response:failed'], body);
            }
          }
        });
      }
    };

    setInterval(process, 1000);

---
kind: workflow
name: runner-requester
breed: runner-requester
schedule: daemon